import type { Profile, Simulation } from '../types';
import { EnvironmentFields } from './EnvironmentFields';
export function SimulationForm({value: s, profile, onChange, onReview, busy}: {
  value: Simulation; profile: Profile; onChange: (s: Simulation) => void; onReview: () => void; busy: boolean;
}) {
  function set<K extends keyof Simulation>(key: K, value: Simulation[K]) { onChange({...s, [key]: value}); }
  return <form onSubmit={e => {e.preventDefault(); onReview();}} className="form-stack">
    <section className="card"><div className="section-title"><span className="step">01</span><div><h2>Choose your workflow</h2><p>Run the AmberMDrun tools from MDSims.</p></div></div>
      <div className="workflow-choices"><button type="button" className={'workflow ' + (s.workflow === 'md' ? 'selected' : '')} onClick={() => onChange({...s, workflow: 'md', temperature: 298.15})} aria-pressed={s.workflow === 'md'}><strong>Molecular dynamics</strong><span>Topology + coordinates → MD trajectory</span></button><button type="button" className={'workflow ' + (s.workflow === 'mmpbsa' ? 'selected' : '')} onClick={() => onChange({...s, workflow: 'mmpbsa', temperature: 303.15})} aria-pressed={s.workflow === 'mmpbsa'}><strong>MM-PB(GB)SA</strong><span>Protein + ligands → MD + binding energies</span></button></div>
      <label>Job name<input value={s.name} onChange={e => set('name', e.target.value)} required pattern="[A-Za-z][A-Za-z0-9_\-]{0,47}" maxLength={48}/></label>
    </section>
    <section className="card"><div className="section-title"><span className="step">02</span><div><h2>Simulation inputs</h2><p>Absolute paths to files already on BP1, inside <code>{profile.root}</code>.</p></div></div>
      {s.workflow === 'md' ? <><label>Topology · PARM7 / PRMTOP<input value={s.topology} onChange={e => set('topology', e.target.value)} placeholder={`${profile.root}/my-system/system.parm7`} required /></label><label>Coordinates · RST7 / INPCRD<input value={s.coordinates} onChange={e => set('coordinates', e.target.value)} placeholder={`${profile.root}/my-system/system.rst7`} required /></label></> : <><label>Protein · PDB<input value={s.protein} onChange={e => set('protein', e.target.value)} placeholder={`${profile.root}/my-system/protein.pdb`} required /></label>
        {s.ligands.map((lig, i) => <div className="ligand" key={i}><label>Ligand {i + 1} · MOL2<input value={lig.path} onChange={e => set('ligands', s.ligands.map((l, j) => j === i ? {...l, path: e.target.value} : l))} required /></label>{s.charge_mode === 'explicit' && <div className="fields"><label>Net charge<input type="number" min={-20} max={20} value={lig.charge} onChange={e => set('ligands', s.ligands.map((l, j) => j === i ? {...l, charge: +e.target.value} : l))} required /></label><label>Multiplicity<input type="number" min={1} max={10} value={lig.multiplicity} onChange={e => set('ligands', s.ligands.map((l, j) => j === i ? {...l, multiplicity: +e.target.value} : l))} required /></label></div>}{s.ligands.length > 1 && <button type="button" className="text-button" onClick={() => set('ligands', s.ligands.filter((_, j) => i !== j))}>Remove ligand {i + 1}</button>}</div>)}
        <button type="button" className="secondary" disabled={s.ligands.length >= 20} onClick={() => set('ligands', [...s.ligands, {path: '', charge: 0, multiplicity: 1}])}>+ Add ligand</button><label>Ligand charges<select value={s.charge_mode} onChange={e => set('charge_mode', e.target.value as Simulation['charge_mode'])}><option value="explicit">Specify charge and multiplicity</option><option value="guess">Let ACPYPE estimate charges</option><option value="file">Use charges in MOL2 files</option></select></label><p className="muted">Ligands must have appropriate hydrogens and be positioned with the protein. The portal does not validate molecular geometry.</p></>}
      <div className="fields"><label>Temperature · K<input type="number" step="0.01" min={1} max={1000} value={s.temperature} onChange={e => set('temperature', +e.target.value)} required /></label><label>Production duration · ns<input type="number" min={1} max={100000} value={s.duration_ns} onChange={e => set('duration_ns', +e.target.value)} required /></label></div>
      {s.workflow === 'md' && <label className="check"><input type="checkbox" checked={s.gamd} onChange={e => set('gamd', e.target.checked)}/> Use Gaussian accelerated MD (GaMD)</label>}
    </section>
    <section className="card"><div className="section-title"><span className="step">03</span><div><h2>BP1 allocation</h2><p>One node per simulation. Walltime includes preparation and equilibration.</p></div></div>
      <div className="fields"><label>Slurm project<input list="accounts" value={s.account} onChange={e => set('account', e.target.value)} placeholder="Your Slurm project account" required/><datalist id="accounts">{profile.accounts.map(a => <option key={a} value={a}/>)}</datalist></label><label>Partition<input list="partitions" value={s.partition} onChange={e => set('partition', e.target.value)} required/><datalist id="partitions">{profile.partitions.map(p => <option key={p} value={p}/>)}</datalist></label></div>
      <label>Amber engine<select value={s.engine} onChange={e => set('engine', e.target.value as Simulation['engine'])}><option value="gpu">GPU · pmemd.cuda + pmemd.cuda_DPFP · 1 GPU</option><option value="cpu">CPU · serial sander</option></select></label>
      <EnvironmentFields spec={s} username={profile.bp1_user} onChange={onChange}/>
      <div className="fields three"><label>CPUs<input type="number" min={1} max={profile.max_cpus} value={s.cpus} onChange={e => set('cpus', +e.target.value)} required /></label><label>Memory · GB<input type="number" min={1} max={profile.max_memory_gb} value={s.memory_gb} onChange={e => set('memory_gb', +e.target.value)} required /></label><label>Walltime<input value={s.walltime} onChange={e => set('walltime', e.target.value)} placeholder="1-00:00:00" required /></label></div><p className="muted">Use HH:MM:SS or D-HH:MM:SS, up to {profile.max_hours} hours. CPU MD uses serial sander. MM-PB(GB)SA analysis uses the requested CPU count.</p>
      <label>Run parent directory<input value={s.run_parent} onChange={e => set('run_parent', e.target.value)} required /></label><p className="muted">An existing BP1 directory inside your work root. Each submission creates its own subdirectory here.</p>
      <details><summary>Notifications & scheduling options</summary><label>Email on completion or failure<input type="email" value={s.mail_user} onChange={e => set('mail_user', e.target.value)} placeholder="Optional" /></label><label>Job dependency<input value={s.dependency} onChange={e => set('dependency', e.target.value)} placeholder="afterok:12345" /></label><div className="fields"><label>QoS<input value={s.qos} onChange={e => set('qos', e.target.value)} placeholder="Optional"/></label><label>Reservation<input value={s.reservation} onChange={e => set('reservation', e.target.value)} placeholder="Optional"/></label></div><label className="check"><input type="checkbox" checked={s.exclusive} onChange={e => set('exclusive', e.target.checked)}/> Request exclusive node access</label></details>
    </section><button className="review-button" disabled={busy}>{busy ? 'Checking inputs…' : 'Check inputs & review script →'}</button>
  </form>;
}
